baseURL = 'https://illogicalfallacy.org/'
locale = 'en-us'
title = 'Illogical Fallacy'
enableRobotsTXT = true

[params]
  description = 'A practical reference guide to logical fallacies.'
  author = 'Illogical Fallacy'

[taxonomies]
  category = 'categories'
  tag = 'tags'
